stages:
  - dry-run
  - lab-test
  - deploy
  - post-deploy

default:
  image: python:3.12.4
  tags:
    - docker
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install --force-reinstall -e .

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: "fetch"

sync-dry-run:
  stage: dry-run
  script:
    - "infra-auto nornir sync-from --dry-run"
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH =~ /^sync\//'
      when: always
