stages:
  - build

build-docker-image:
  stage: build
  image: docker:24.0.5
  variables:
    DOCKER_HOST: "unix:///runner/services/docker/docker.sock"
    IMAGE_NAME: "a60814billy/infra-auto"
    IMAGE_TAG: "latest"
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add --no-cache git
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker info
  script:
    - find . 
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  after_script:
    - docker logout
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"
  tags:
    - ain-lab
