stages:
  - dry-run
  - deploy

default:
  image: python:3.12.4
  tags:
    - docker
  cache:                      # Pip's cache doesn't store the python packages
    paths:                    # https://pip.pypa.io/en/stable/topics/caching/
      - .cache/pip
  before_script:
    - pip install -r requirements.txt

variables:  # Change pip's cache directory to be inside the project directory because we can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

nornir-dry-run:
  stage: dry-run
  image: python:3.12.4
  script:
    - python3 nornir_sync_cfg_to_devices.py --dry-run | tee -a .dry_run_output
  after_script:
    - python3 report_changes.py
  tags:
    - docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

nornir-apply:
  stage: deploy
  image: python:3.12.4
  script:
    - python3 nornir_sync_cfg_to_devices.py
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      when: always
