stages:
  - trigger

trigger-sync-pipeline:
  stage: trigger
  trigger:
    include: ci/sync-pipeline.yml
  rules:
    # Trigger child pipeline for MRs with source or target branch matching sync/*
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"
