stages:
  - dry-run
  - deploy
  - post-deploy

default:
  image: python:3.12.4
  tags:
    - docker
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install -e .

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

nornir-dry-run:
  stage: dry-run
  script:
    - python3 utility/detect_cfg_change_in_mr.py
    - infra-auto nornir apply --dry-run | tee -a .dry_run_output
    # Remove terminal color codes from the output
    - sed -i -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" .dry_run_output
  after_script:
    - python3 utility/report_changes.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  
nornir-apply:
  stage: deploy
  script:
    - python3 utility/detect_cfg_change_in_mr.py
    - infra-auto nornir apply
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      when: always

sync-configs-from-devices:
  stage: post-deploy
  script:
    - |
      if [ -n "$CHANGE_DEVICE_LIST" ]; then
        echo "$CHANGE_DEVICE_LIST" > .change_device_list
        echo "Received device list from parent pipeline: $CHANGE_DEVICE_LIST"
      else
        echo "No device list received from parent pipeline"
      fi
    - python3 nornir_sync_cfg_from_devices.py
    - git diff cfg/
  rules:
    - if: $CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  allow_failure: true
