stages:
  - detect-changes
  - dry-run
  - deploy
  - post-deploy

default:
  image: python:3.12.4
  tags:
    - docker
  cache:                      # Pip's cache doesn't store the python packages
    paths:                    # https://pip.pypa.io/en/stable/topics/caching/
      - .cache/pip
  before_script:
    - pip install -r requirements.txt

variables:  # Change pip's cache directory to be inside the project directory because we can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

detect-mr-devices:
  stage: detect-changes
  script:
    - python3 detect_cfg_change_in_mr.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
      when: always
  artifacts:
    paths:
      - .change_device_list

nornir-dry-run:
  stage: dry-run
  script:
    - python3 nornir_sync_cfg_to_devices.py --dry-run | tee -a .dry_run_output
  after_script:
    - python3 report_changes.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  

nornir-apply:
  stage: deploy
  script:
    - python3 nornir_sync_cfg_to_devices.py
  after_script:
    - python3 trigger_post_deploy.py
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      when: always
  needs:
    - job: detect-mr-devices
      artifacts: true

sync-configs-from-devices:
  stage: post-deploy
  script:
    - |
      if [ -n "$CHANGE_DEVICE_LIST" ]; then
        echo "$CHANGE_DEVICE_LIST" > .change_device_list
        echo "Received device list from parent pipeline: $CHANGE_DEVICE_LIST"
      else
        echo "No device list received from parent pipeline"
      fi
    - python3 nornir_sync_cfg_from_devices.py
    - git config --global user.email "gitlab-ci@example.com"
    - git config --global user.name "GitLab CI"
    - git add cfg/
    - |
      if git diff --cached --quiet; then
        echo "No changes to commit"
      else
        # Use GITLAB_PUSH_TOKEN (should be set as a protected CI/CD variable with write_repository scope)
        git commit -m "Update device configurations [skip ci]"
        
        # Try different push methods in order of preference
        if [ -n "$GITLAB_API_TOKEN" ]; then
          echo "Using GITLAB_API_TOKEN for authentication"
          git push http://CI:${GITLAB_API_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:main
        fi
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "api" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  allow_failure: true
