tndo-c8k-1:
  hostname: 10.192.4.181
  username: admin
  password: 1234@QWer!
  platform: ios

tndo-c8k-2:
  hostname: 10.192.4.182
  username: admin
  password: 1234@QWer!
  platform: ios

tndo-n9k-1:
  hostname: 10.192.4.183
  username: admin
  password: 1234@QWer!
  platform: nxos_ssh

tndo-n9k-2:
  hostname: 10.192.4.184
  username: admin
  password: 1234@QWer!
  platform: nxos_ssh

tndo-xrv-1:
  hostname: 10.192.4.185
  username: admin
  password: 1234@QWer!
  platform: iosxr

tndo-xrv-2:
  hostname: 10.192.4.186
  username: admin
  password: 1234@QWer!
  platform: iosxr